# Generated by Django 4.2.5 on 2023-09-27 23:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=500)),
                ('link', models.URLField(max_length=256, null=True)),
                ('pdf', models.FileField(upload_to='')),
                ('foto', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('fecha_maxima', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('numero', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('cv', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'])])),
                ('puesto', models.IntegerField(choices=[('1', 'Obrero'), ('2', 'Maestro mayor'), ('3', 'Arquitecto'), ('4', 'Ingeniero'), ('5', 'Renderista'), ('6', 'Maquetista'), ('7', 'Otro')], max_length=1)),
            ],
        ),
    ]
