# Generated by Django 4.2.5 on 2023-10-09 14:53

import app_arq.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_arq', '0002_proyecto_user_alter_proyecto_fecha_maxima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='link',
            field=models.URLField(max_length=256),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='pdf',
            field=models.FileField(upload_to=app_arq.models.pdf_upload_to),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='cv',
            field=models.FileField(upload_to=app_arq.models.cv_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='puesto',
            field=models.IntegerField(choices=[(1, 'Obrero'), (2, 'Maestro mayor'), (3, 'Arquitecto'), (4, 'Ingeniero'), (5, 'Renderista'), (6, 'Maquetista'), (7, 'Otro')]),
        ),
    ]
