# Generated by Django 4.2.5 on 2023-10-09 16:58

import app_arq.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_arq', '0003_trabajador_user_alter_proyecto_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='disponibilidad',
            field=models.IntegerField(choices=[(1, 'Semana'), (2, 'Fin de Semana'), (3, 'Total')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trabajador',
            name='horario',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Total')], default=1),
            preserve_default=False,
        ),
    ]
