# Generated by Django 4.2.5 on 2023-10-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_arq', '0004_trabajador_disponibilidad_trabajador_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='fecha_maxima',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='foto',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='inversion',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='disponibilidad',
            field=models.IntegerField(choices=[(1, 'Semana'), (2, 'Fin de Semana'), (3, 'Total')], default=3),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='horario',
            field=models.IntegerField(choices=[(1, 'Mañana'), (2, 'Tarde'), (3, 'Total')], default=3),
        ),
    ]
